Merging to feature abstractions
SummitML/kaggle-audio-tagging pull request #13
Opened 2018-07-07 23:55 UTC by changhsinlee

I think I messed up merging features abstractions + develop + my own branch, and I can't automatically merge between develop and my branch.

Tested the idea of a simple stacked model.

2018-07-07 23:56 UTC, changhsinlee commented
@crodriguez1a if you could merge this into develop please show me how to 😭I saw 15 file merge conflicts...

2018-07-08 10:45 UTC, crodriguez1a commented
@changhsinlee I made quite a few more commits.  You'll want to re-base and make sure I haven't broken anything for you. Tests were passing, so you should be fine.

2018-07-08 11:05 UTC, crodriguez1a requested changes
Pull down the latest commits and re-validate.

2018-07-08 11:11 UTC, crodriguez1a commented on notebooks/chang/1.4-logisitic-regression-on-all-files.ipynb
> +    "        pickle.dump(wav_data, f)\n",
@changhsinlee 👍

2018-07-08 11:11 UTC, crodriguez1a commented on notebooks/chang/1.4-logisitic-regression-on-all-files.ipynb
> +    "    with open('data/raw/train/wav-data-{}.pkl'.format(tag_name), 'wb') as f:\n",
@changhsinlee As of 3.6, you can use string literals to concatenate 

```python
with open(f'data/raw/train/wav-data-{tag_name}.pkl', 'wb') as f:
```

2018-07-08 14:42 UTC, crodriguez1a commented
Closing while we sort out commit history

2018-07-08 14:42 UTC, closed without merging